// Deterministic solution matching — code only, never the model.
//
// Qualification already separates OBSERVED (evidenced) capability matches from
// INFERRED ones (lib/qualification/types.ts: applyEvidenceDiscipline). This
// module goes one step further: it maps those VERIFIED capabilities onto the
// fixed solution catalog (lib/solutions/catalog.ts) using a plain lookup, so
// "which product do we recommend" is never a judgment call the LLM makes.
//
// A capability with no evidence, or a solution not present in the catalog,
// can never win a match — there is no path from "the model thinks this fits"
// to a solution being recommended.

import type { TargetQualification } from '@/lib/qualification/types';
import { getSolutionCatalog } from './catalog';
import type { MatchedCapability, SolutionMatch, ZampSolution } from './types';

export { NO_SOLUTION_MATCH_MESSAGE } from './types';

/**
 * Match verified company capabilities to the single best-fitting approved
 * solution.
 *
 * Only OBSERVED capability matches with surviving verified evidence are
 * eligible (the same set `capabilityContext()` in lib/pipeline/stages.ts
 * treats as "actually shown to have" — inferred-only capabilities never
 * reach this function). A solution is eligible when it lists at least one
 * of those capability ids in `matches_capability_ids`; among eligible
 * solutions, the one with the highest summed `fit_strength` across its
 * matched capabilities wins. Ties break on catalog order (first declared),
 * so the result is always the same for the same inputs.
 */
export function matchApprovedSolution(
  qualification: TargetQualification | null | undefined,
  catalog: ZampSolution[] = getSolutionCatalog(),
): SolutionMatch | null {
  const matches = qualification?.company_fit.capability_matches ?? [];
  const observed = matches.filter((m) => m.basis === 'OBSERVED' && m.evidence.length > 0);
  if (observed.length === 0) return null;

  let best: { solution: ZampSolution; score: number; matched: MatchedCapability[] } | null = null;

  for (const solution of catalog) {
    const matched = observed.filter((m) => solution.matches_capability_ids.includes(m.capability_id));
    if (matched.length === 0) continue;

    const score = matched.reduce((sum, m) => sum + m.fit_strength, 0);
    if (best && score <= best.score) continue;

    best = {
      solution,
      score,
      matched: matched
        .map((m) => ({
          capability_id: m.capability_id,
          capability_name: m.capability_name,
          company_signal: m.company_signal,
          fit_strength: m.fit_strength,
          evidence: m.evidence,
        }))
        .sort((a, b) => b.fit_strength - a.fit_strength),
    };
  }

  if (!best) return null;

  return {
    solution: best.solution,
    matched_capabilities: best.matched,
    why_it_fits: describeFit(best.solution, best.matched),
  };
}

/** Plain, evidence-grounded sentence — assembled from verified data, never generated by a model. */
function describeFit(solution: ZampSolution, matched: MatchedCapability[]): string {
  const detail = matched
    .map((m) => `${m.capability_name} (${m.company_signal})`)
    .join('; ');
  return `${solution.name} addresses ${detail} — a verified, evidenced workflow at this company.`;
}

/** What the model is allowed to see: name, description and boundaries. Never redefinable. */
export interface ApprovedSolutionContext {
  id: string;
  name: string;
  description: string;
  target_functions: string[];
  use_cases: string[];
  non_use_cases: string[];
  matched_on: string[];
}

/** Prompt-safe projection of a match — the model may use this, never expand it. */
export function solutionForPrompt(match: SolutionMatch): ApprovedSolutionContext {
  return {
    id: match.solution.id,
    name: match.solution.name,
    description: match.solution.description,
    target_functions: match.solution.target_functions,
    use_cases: match.solution.use_cases,
    non_use_cases: match.solution.non_use_cases,
    matched_on: match.matched_capabilities.map((m) => m.capability_name),
  };
}
